### ISSUE TITLE
Model design

### ISSUE THREAD

**Issue by bgdxqi** [AMIOL7/ELME#1]

**Comment by vismate** [comment]
The design shown below has been implemented and pushed ([commit](https://github.com/AMIOL7/ELME/commit/57a8199562327c64fa6297b30f86ad41074eb781)) to brach ['abstract-part-of-model'](https://github.com/AMIOL7/ELME/tree/abstract-part-of-model).

![image](https://user-images.githubusercontent.com/70141135/196468724-4787707c-40b7-45af-a1c1-68892fcb2be2.png)

**Comment by AMIOL7** [comment]
If you want it merged to main, please create a pull request and mark people you want to review it

**Comment by bgdxqi** [comment]
I think we forgot about setting the values in both ports.
