### ISSUE TITLE
Model.OutputPort.setValue(boolean value) fails beacuse of wrong argument type

### ISSUE THREAD

**Issue by vismate** [AMIOL7/ELME#12]
In [this commit](https://github.com/AMIOL7/ELME/commit/adf56e5722e41979341bc59d8c0e666424334ad1) we switched from using ```boolean``` to ```Boolean``` (boxed type) as it enables us to use a 3rd value (```null```). We use ```null``` to indicate if a Node cannot be evaluated because of no or invalid inputs. However we forgot to change ```Model.OutputPort.setValue(boolean value)``` to accept the boxed version as parameter. This results in a sneaky error (```java.lang.NullPointerException```) when a ```null``` (an otherwise valid) value is passed as argument. Java tries to coerce ```Boolean``` to ```boolean``` which then of course fails.

I propose fixing this and all future issues like this by switching to ```Optional<Boolean>``` - a more functional pattern - that explicitly expresses the 3rd state. It would also prevent unexpected type coercions.

**Comment by bgdxqi** [comment]
Have not really heard about Optional<> yet, but sounds reasonable, especially in our case.
