### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by vismate** [AMIOL7/ELME#13]
We got this suggestion from Szalay Richárd:
> Just a general suggestion: it is not a good idea to have multiple top-level packages if you are developing "one" application. So having an "ELME" and a "MODEL" package is a bit redundant, conventionally there is a top-level package, and then subpackages, like "elme.model", "elme.graphics", etc.

Should we restructure our project? If so, how? Should we do it now, or should we wait for merging more of the active branches?

**Comment by AMIOL7** [comment]
We can just make a small fix in master branch now. And I will make same change in my camera control branch

**Comment by bgdxqi** [comment]
Yes, probably would be worth listening to the suggestion. As it is not all that big of a change, I share Andrey's idea. If things go south, we should be able to handle the conflict as (as I already said) would not be too big of a change. On the other hand, if you plan to merge with main in the following days, I think we can wait until that.

**Comment by vismate** [comment]
I have just created a branch for [this issue](https://github.com/AMIOL7/ELME/issues/12). It could possible be merged today, after that the change could be made.

**Comment by AMIOL7** [comment]
Since the branch that you created, has been merged, I believe now it is possible to change the location of model directory @vismate

**Comment by vismate** [comment]
Yes, we should do it now.
