### ISSUE TITLE
Testing the model

### ISSUE THREAD

**Issue by vismate** [AMIOL7/ELME#14]
#### We should test:

- No input connection
- Invalid input value
- Built-in node correctness
- What happens if there is a cycle in the graph

Are there any ideas what else should be tested in the current implementation?

**Comment by AMIOL7** [comment]
I think, it would be nice to test the evaluation of the graph @vismate

**Comment by bgdxqi** [comment]
Some tests have been created checking the connections of the nodes and the built-in node correctness. 2 Issues have been found, both got fixed.
