### ISSUE TITLE
UI design and framework

### ISSUE THREAD

**Issue by pszi** [AMIOL7/ELME#2]
Beginning work on static components on the screen, part of View.

**Comment by vismate** [comment]
@pszi Did you manage to make any progress on this issue? Could you please describe what plans you've got for the UI?

**Comment by pszi** [comment]
The user interface's design could be the following:
- On top would be a floating toolbar where basic operations (such as save, load, new graph) would be accessible.
- On the left side would be another floating tabbed bar where both basic logic gates as well as saved (sub)graphs could be imported from via drag-and-drop.
- These two would be recessed into the sides of the screen, only coming out when the cursor hovers over them, also by default it would have high transparency but it would become temporarily opaque when it's out.

**Comment by vismate** [comment]
Sounds good to me!

**Comment by vismate** [comment]
Just tried running the linked branch. I like the layout, can't wait to see it implemented. One thing I noticed (though this might be just temporary) your sketch-up moves when I pan the camera. It should be an overlay. Do you know how you'll going to achieve it?

**Comment by pszi** [comment]
The previous design was just an illustration, now that I've figured out how to draw GUI components on the screen, it will be properly implemented shortly.

**Comment by pszi** [comment]
I think this can be considered to be done, the menus are in the correct places.
