### ISSUE TITLE
Access to graphs and nodes from the outside

### ISSUE THREAD

**Issue by pszi** [AMIOL7/ELME#23]
@vismate To be able to draw a graph and its nodes on screen with the correct information and to later be able to manipulate them, there needs to be a way to access a graph's nodes, which are, at the moment, private. Please implement getters and setters in the Port, Node and Graph classes.

**Comment by vismate** [comment]
Okay, I'll go and implement getters soon. It'll be done by around 3, if you want to work on it today.

**Comment by pszi** [comment]
Okay, thanks for the heads-up, I will.

**Comment by pszi** [comment]
looks good, thank you.

**Comment by pszi** [comment]
Error: Graph's "nodes" field not initialized in constructor. Please fix.

**Comment by pszi** [comment]
Also, could you please do add/remove element operations for array fields instead of just a setter?

**Comment by vismate** [comment]
As we just merged the branch, we'll have to do it later. Is it urgent or can it wait?

**Comment by pszi** [comment]
Yes, it's not that important right now. In fact I'll close this issue and open another one for that.
