### ISSUE TITLE
Failed test cases; where should the fixes go?

### ISSUE THREAD

**Issue by vismate** [AMIOL7/ELME#29]
After resolving [this issue](https://github.com/AMIOL7/ELME/issues/28) I found failing test cases. I made the fixes but I'm unsure whether I should create a new branch, push directly into ```main``` (as its just a single line + a single character change) or commit them to the ```model-test``` branch, as thats what I'm currently working on.

**Comment by AMIOL7** [comment]
@vismate I think it should can be committed directly to main, but a separate branch can also be good

**Comment by bgdxqi** [comment]
Separate branch has been made and merged to main. #30
