### ISSUE TITLE
Implement the simulation

### ISSUE THREAD

**Issue by AMIOL7** [AMIOL7/ELME#35]

**Comment by vismate** [comment]
I'd like to link issue #38.

**Comment by vismate** [comment]
What I did so far: 
- Added ```owner``` field and respective getter/setter to ```Port```
- ```Node```s now keep track of their dependents (forming a higher level graph than individual ports)
- Changed how ```InputNode.connect(port)``` behaves: **It now only connects to port, if it is in a disconnected state atm**
- Implemented ```Node.triggerDonwlineUpdate()``` requested in #38 
- Implemented ```Node.inCycle()``` requested in #38 
- Wrote some tests to check the aforementioned methods' correctness
- Node dependency: ```Node.directDependencyOf(node)```, ```Node.transitiveDependencyOf(node)```

On the linked branch you'll soon be able to see these changes. I highly consider this an experimental branch/solution so I request your ideas, alternatives and opinion on these changes.

**Comment by pszi** [comment]
> * Changed how `InputNode.connect(port)` behaves: **It now only connects to port, if it is in a disconnected state atm**

This will alter behavior of my use of it in the view, it is easily fixable though, consider this only as a "note to self".

As for the rest, they will come extremely handy, thank you.

**Comment by vismate** [comment]
> > * Changed how `InputNode.connect(port)` behaves: **It now only connects to port, if it is in a disconnected state atm**
> 
> This will alter behavior of my use of it in the view, it is easily fixable though, consider this only as a "note to self".
> 
> As for the rest, they will come extremely handy, thank you.

I can also fix this issue on my side in 2 lines. At the time of writing the comment above it was easier to change the behaviour, especially because I though it would not affect anything.

Since then I have the infrastructure to change it back in no time.
