### ISSUE TITLE
Is branch beginning-and-ending-nodes complete?

### ISSUE THREAD

**Issue by vismate** [AMIOL7/ELME#39]
@bgdxqi, you've been working on said branch. Is it ready or have you got plans to add more to it? It'd be nice to merge it into main and use it to expand the view/visualization with switches and light bulbs.

**Comment by pszi** [comment]
@vismate, is it ready on your part? Because we can merge it into my branch, I can work without these ones for now.

**Comment by bgdxqi** [comment]
I thought of adding a Switch but that needs work on the View side as well. In which I have no experience yet. If we don't want it, then we can just merge.

**Comment by pszi** [comment]
A switch can simply be a node that has a value set at the constructor and a method to toggle said value. I can make the rest work.

**Comment by vismate** [comment]
> @vismate, is it ready on your part? Because we can merge it into my branch, I can work without these ones for now.

I've only been working on the model on branch ```model-simulation```. If you are thinking of that, then it's still missimg some stuff.

I'll probably start working on the terminus nodes in the view tomorrow or later tonight.

**Comment by pszi** [comment]
Okay, I can handle the view part if you want, but you can do it too if you wish.

**Comment by vismate** [comment]
> Okay, I can handle the view part if you want, but you can do it too if you wish.

I think it depends more on your schedual. 

What we could do is I work on switches and light bulbs in the view consulting you as needed. @bgdxqi could step in for me in the model. You could work on some view enhancements, menus or whatever you see fit.

**Comment by bgdxqi** [comment]
Fine by me!

**Comment by pszi** [comment]
I don't really have ideas as to what else I could do on the view side, sooo... okay maybe one thing but I don't know it that's possible. My schedule was seeming good a few hours ago but something happened in my private life which may upset everything so it's unfortunately not looking good. I'll leave things up to you then.

**Comment by pszi** [comment]
Status update: My schedule is looking a lot better now, I can work a little more on the project if any one of you need me for something.

**Comment by vismate** [comment]
Branch is now merged, closing issue.
