### ISSUE TITLE
Code style and javadoc usage

### ISSUE THREAD

**Issue by vismate** [AMIOL7/ELME#4]
I propose following the java code style implied by netbeans, furthermore I recommend that we enforce the proper use of javadoc.
Classes, interfaces and methods should be documented by stating their purpose, arguments and returns. (where these apply).

**Comment by AMIOL7** [comment]
I agree

**Comment by pszi** [comment]
Understood.

**Comment by vismate** [comment]
As we either implicitly or explicitly agreed to this, I am closing this issue now.
