### ISSUE TITLE
view-enhancement branch goal and ready-ness

### ISSUE THREAD

**Issue by vismate** [AMIOL7/ELME#41]
I'm ready to start implementing terminating nodes (switches and lights) into the view and I was wondering whether it would be appropriate to continue this branch or start a separate one. 

If you recommend implementing those in their own branch, should we merge these changes to main first (If this branch is considered complete by it's author)?

I'd also like to use additions from branch [```beginning-and-ending-nodes```](https://github.com/AMIOL7/ELME/tree/beginning-and-ending-nodes) so we should keep that in mind.

**Comment by pszi** [comment]
I believe it to be ready for continuation. You could either merge the now updated main into the branch or merge this into main then rebase main onto this branch. Both options have the same result, but the first option is less steps so I'd go with that.
