### ISSUE TITLE
Generate truth table

### ISSUE THREAD

**Issue by AMIOL7** [AMIOL7/ELME#45]
To save a custom made graph we have decided to use truth tables. This issue is about threating a function that will generate such truth table for any given graph. The logic is to use functions that return free input and output ports, and use evaluate method of graph to note the values of free output ports for every possible value of free input ports. The return of the function would be a map with input as key and corresponding output as value.

**Comment by AMIOL7** [comment]
@vismate @pszi @bgdxqi Opinions, ideas, suggestions, questions?

**Comment by vismate** [comment]
We need to be able to evaluate a graph from the very beginning. Our idea was, to initiate a downline update from every single node that has free inputs. This needs to be done in the right order (topological order) to have the desired effect.

In the light of this, we need the branch merged (or base the feature branch on it) where @bgdxqi works on these.

**Comment by AMIOL7** [comment]
> We need to be able to evaluate a graph from the very beginning. Our idea was, to initiate a downline update from every single node that has free inputs. This needs to be done in the right order (topological order) to have the desired effect.
> 
> In the light of this, we need the branch merged (or base the feature branch on it) where @bgdxqi works on these.

What is the name of the branch? I will base my feature branch on it and later merge to it

**Comment by vismate** [comment]
> > We need to be able to evaluate a graph from the very beginning. Our idea was, to initiate a downline update from every single node that has free inputs. This needs to be done in the right order (topological order) to have the desired effect.
> > 
> > In the light of this, we need the branch merged (or base the feature branch on it) where @bgdxqi works on these.
> 
> What is the name of the branch? I will base my feature branch on it and later merge to it

model-simulation
