### ISSUE TITLE
Documentation and expanded readme

### ISSUE THREAD

**Issue by vismate** [AMIOL7/ELME#46]
As per the upcoming assignment requirement I'd like to expand the README with information about downloading releases and running them on different platforms.

We're also required to create a documentation about our app and how to use it, Because we are still working on new features, I'll only merge the associated branch once we are ready to submit the assignment.

I'd also like to ask someone owning a windows machine to try running one of the releases using the ELME.bat file.

**Comment by bgdxqi** [comment]
Works like a charm on my Win10
