### ISSUE TITLE
Naming convention of predefined logic nodes

### ISSUE THREAD

**Issue by vismate** [AMIOL7/ELME#5]
### My suggestions: 

- ```InputPort```s
  - If no obvious names come to mind: A, B, C...Z (capital letters of the english alphabet)
- ```OutputPort```s
  - If no obvious names come to mind:
    - Out, if there is only one output
    - Out 1, Out 2, ... otherwise 
   
@bgdxqi Please leave your opinion below, as you are in charge of implementing predefined nodes.

**Comment by AMIOL7** [comment]
Good idea

**Comment by bgdxqi** [comment]
I support it

**Comment by vismate** [comment]
As the majority agrees with this convention, including @bgdxqi - the the one in charge of related branch - I am now closing this issue.

**Comment by bgdxqi** [comment]
**The issue was further discussed, and we reached a conclusion. The naming convention is:** 
- In1, In2, In3... for inputPorts 
- Out1, Out2, Out3... for outputPorts
