### ISSUE TITLE
Merging and closing our major branches.

### ISSUE THREAD

**Issue by vismate** [AMIOL7/ELME#52]
Many of our branches (namely ```experimental-view-with-simulation```,```topological-evaluation```,```view-enhancement```,```model-simulation```) are done by this point, so we should work on merging them into main. Because all of us had worked on these branches I'm opening this issue to notify everybody of our plan. Please do not start any new work on these branches.

First, we'll merge ```experimental-view-with-simulation``` into ```main```
Then, we'll merge ```topological-evaluation``` into ```main```
We'll close ```view-enhancement``` and ```model-simulation```,  since all their latest changes will be merged to ```main``` through branches above.

**Comment by AMIOL7** [comment]
Is this issue done?

**Comment by vismate** [comment]
> Is this issue done?

No, we haven't dond the merges yet.

**Comment by pszi** [comment]
We have done the merges now, can I proceed with deleting the left over branches?

**Comment by AMIOL7** [comment]
> We have done the merges now, can I proceed with deleting the left over branches?

Go ahead

**Comment by bgdxqi** [comment]
Think so

**Comment by pszi** [comment]
Okay, it is done.

**Comment by pszi** [comment]
Um, if you would please close the associated issues too. Thank you.
