### ISSUE TITLE
Reaching consensus on coloring choice

### ISSUE THREAD

**Issue by pszi** [AMIOL7/ELME#53]
Let's discuss below each of our ideas and suggestions on how to choose colors for the statuses of nodes and links.
There are three colors needed: disconnected, true and false.

**Comment by vismate** [comment]
In my view, red is something "bad, false, error", green is "all good, true, signal" and black (grey) is "inactive, not connected"

With this in mind I propose the following: green for true, red for false, black for no signal

**Comment by AMIOL7** [comment]
Why not just do color for signal, and no color (grey) when no signal

**Comment by bgdxqi** [comment]
I support Máté's idea. We could do just 1 color as well, as Andrey suggested, but providing as much feedback as possible through simple shapes and colours are always handy in my opinion. Furthermore all the required code is done for supporting 3 colours.

**Comment by AMIOL7** [comment]
I am not sure, if marking no signal with red is a good idea. Returning to Mate's comment, red is "bad", but no signal is not bad

**Comment by AMIOL7** [comment]
> In my view, red is something "bad, false, error", green is "all good, true, signal" and black (grey) is "inactive, not connected"
> 
> With this in mind I propose the following: green for true, red for false, black for no signal

In signals True is 1, False is 0. There is no third option

**Comment by bgdxqi** [comment]
I think of it more like 1=True=green, 0=False=red, null=no signal=grey

**Comment by pszi** [comment]
In our implementation, a port not connected does not equal a false evaluation. There is no reason to fuse "no value" with "false", it just wouldn't make sense.

**Comment by AMIOL7** [comment]
> I think of it more like 1=True=green, 0=False=red, null=no signal=grey

But signal is binary. If the node is False, then there is no signal.

Then again, False is not necessarily "bad" , and True is not necessarily "good". Using red and green may give a wrong message to the user. It would be better to do simple signal and no signal (blue and grey for example)

**Comment by pszi** [comment]
@AMIOL7 I do agree with the red and green analogy you say, but can you please understand that in the model the value is NOT a boolean! It is an Optional(boolean), and it is implemented in the model that way. A missing value is neither true nor false.

**Comment by pszi** [comment]
If we decided to simply use boolean in the model, you'd be right, but we're not using that.

**Comment by AMIOL7** [comment]
> @AMIOL7 I do agree with the red and green analogy you say, but can you please understand that in the model the value is NOT a boolean! It is an Optional(boolean), and it is implemented in the model that way. A missing value is neither true nor false.

The model is Boolean. Optional is just used to handle missing value, but from the point of view of user and in the circuits, missing value is 0 as well as no signal

We don't have to represent everything we have in the model

**Comment by pszi** [comment]
> > @AMIOL7 I do agree with the red and green analogy you say, but can you please understand that in the model the value is NOT a boolean! It is an Optional(boolean), and it is implemented in the model that way. A missing value is neither true nor false.
> 
> The model is Boolean. Optional is just used to handle missing value, but from the point of view of user and in the circuits, missing value is 0 as well as no signal
> 
> We don't have to represent everything we have in the model

What are you talking about? If there is a node that can't be evaluated because one of the ports aren't connected, it carries over to every consecutive node. For example, an OR node with one connected input with true value, and one disconnected input should evaluate to true by your logic, but it doesn't! Try it for yourself!

**Comment by AMIOL7** [comment]
> > > @AMIOL7 I do agree with the red and green analogy you say, but can you please understand that in the model the value is NOT a boolean! It is an Optional(boolean), and it is implemented in the model that way. A missing value is neither true nor false.
> 
> > 
> 
> > The model is Boolean. Optional is just used to handle missing value, but from the point of view of user and in the circuits, missing value is 0 as well as no signal
> 
> > 
> 
> > We don't have to represent everything we have in the model
> 
> 
> 
> What are you talking about? If there is a node that can't be evaluated because one of the ports aren't connected, it carries over to every consecutive node. For example, an OR node with one connected input with true value, and one disconnected input should evaluate to true by your logic, but it doesn't! Try it for yourself!

In such case our simulation is incorrect, because OR should evaluate to true with one input

**Comment by bgdxqi** [comment]
Yes. The problem is that we do not allow any input ports to be left out. That's why it gives false, even though IRL it should be true. But i think this just makes our claim more reasonable. Let alone being more user-friendly.  I don't think Andrey's idea is bad though. It pretty much is just about keeping it real vs being user-friendly.

**Comment by bgdxqi** [comment]
@vismate you are the one who knows the most about our evaluation. Do you think we can fix it until the deadline?

**Comment by vismate** [comment]
Sure, its just the matter of changing one method, plus the eval logic of built in nodes. Though, I would not get rid of Optional right now, because all other code uses it. It could be removed later.

**Comment by vismate** [comment]
So whats our final decision about colors?  I'll implement the behavioral changes by tomorrow morning and I'd like the new colors be implemented by tomorrow night, as I'd like to start working on the documentation **with screenshots**.

**Comment by pszi** [comment]
I am sorry @AMIOL7 but I am taking the liberty of vetoing the changing of the implementation to only use two colors, unless someone else takes it upon themselves to refactor the view. I believe it is too late for us to be changing behavior like this, and with the time I have left that I can work on this project I can't guarantee that I can finish the change, and I don't want a large amount of unused code to be just hanging around. And anyways, the others have better things to do in the less than 48 hours left than figure out if the changes don't break tests or other functionality.

That being said, I think we'll close this having decided to use the colors: green for true, red for false, and grey for no information.
