### ISSUE TITLE
Create camera and implement its control

### ISSUE THREAD

**Issue by AMIOL7** [AMIOL7/ELME#6]
Implement the camera that have pan and zoom

**Comment by vismate** [comment]
I've linked this issue to the correct branch. How would you go about implementing this feature?

**Comment by AMIOL7** [comment]
If you take a look in the code, you can see that I have already implemented camera panning, which can be done by dragging the mouse over game screen with right mouse button pressed.
As for zooming feature, my idea is to use scroll wheel to change zoom, but initial attempts have proven difficult

**Comment by vismate** [comment]
I've looked at the code. Looks good to me. I have one question though: panning now works with multiplying the drag direction with a arbitrary speed. Should this speed change with the zoom level? Wouldn't zooming speed up the pan speed relatively?

**Comment by AMIOL7** [comment]
@vismate That is a very good idea, actually. I will do that, but for now my goal is to make zoom work

**Comment by vismate** [comment]
What needs to be done for the zoom to work?

**Comment by AMIOL7** [comment]
Investigation. Camera has getter and setter for zoom, but I have not seen any change when playing around with it

**Comment by vismate** [comment]
I can try and help to investigate tomorrow, as I have no assigned tasks at the moment.

**Comment by AMIOL7** [comment]
Thanks, but I can figure it out on my own. I just need a time slot to sit and do this

**Comment by vismate** [comment]
Just tried running the linked branch. Unfortunately I don't think this approach to implement panning will work.
Problems I came across:

1. Pan speed is not in sync with the way in which I move my mouse. (I think the arbitrary speed you set is only correct for your setup)
2. Panning on both axes is faster than only panning horizontally or vertically. (I think it is the way you set dx and dy in MouseDraggedListener: In cases where you move along both axes the length of the vector (dx, dy)  is not 1 (it is sqrt(2) -> not unit vector) )
3. The app tries to open an image (presumably the one you display to test your code) which we don't store in the repo. (I recommend drawing some shape and/or text instead for now)

I suggest finding a different way to figure out exactly how much we need to pan. (Getting the mouse position with regards to the window itself  and mapping it to view transform maybe?)

For now though a quick fix for 2. would be to normalize (dx, dy) or (current - previous)  directly.

**Comment by vismate** [comment]
>  For now though a quick fix for 2. would be to normalize (dx, dy) or (current - previous) directly.

``` 
@Override
    public void mouseDragged(MouseEvent me) {
        Point2D currentPos =  Input.mouse().getLocation();
        
        double dx = 0, dy = 0;
        if (Input.mouse().isRightButtonPressed()) {
            dx = currentPos.getX() - prevPosition.getX();
            dy = currentPos.getY() - prevPosition.getY();
            
            double len = Math.sqrt(dx*dx + dy*dy);
            if (len > 0.0) { dx /= len; dy /= len; }                       
            
            camPos = new Point2D.Double(camPos.getX() + dx * speed, camPos.getY() + dy * speed);
            cam.pan(camPos, 1);
        }

        prevPosition = currentPos;
        
        
    }
```
This works slightly better in my opinion, but it's still not good enough to adopt.
During more testing I found, that the speed in which you physically move your mouse also determines the pan speed. (The slower you go, the more you pan relatively)

### Here's an abstract idea:
Instead of trying to figure out how much to add to the camera position according to previous and current mouse position, we should "anchor" the cursor to a "physical" location in the scene.  Then we only have to make sure that the anchored location in our scene is always right under the cursor.

If we started thinking about this abstract idea, we could come up with a concrete implementation. (Which might not be the above solution word to word)

**Comment by vismate** [comment]
> Instead of trying to figure out how much to add to the camera position according to previous and current mouse position, we should "anchor" the cursor to a "physical" location in the scene. Then we only have to make sure that the anchored location in our scene is always right under the cursor.

> If we started thinking about this abstract idea, we could come up with a concrete implementation. (Which might not be the above solution word to word)

I just quickly implemented this idea, it works good! No need for a magic speed constant, its accurate with different zoom levels and it tracks your mouse well enough! 

I've implemented it in a scrap project, will show you tomorrow, then you may implement it here as well. (Only if you also think it works well enough)

**Comment by AMIOL7** [comment]
> > Instead of trying to figure out how much to add to the camera position according to previous and current mouse position, we should "anchor" the cursor to a "physical" location in the scene. Then we only have to make sure that the anchored location in our scene is always right under the cursor.
> 
> 
> 
> > If we started thinking about this abstract idea, we could come up with a concrete implementation. (Which might not be the above solution word to word)
> 
> 
> 
> I just quickly implemented this idea, it works good! No need for a magic speed constant, its accurate with different zoom levels and it tracks your mouse well enough! 
> 
> 
> 
> I've implemented it in a scrap project, will show you tomorrow, then you may implement it here as well. (Only if you also think it works well enough)

Can you send me the code, so I can take a look?

**Comment by vismate** [comment]
I uploaded the code in a form of a [gist](https://gist.github.com/vismate/7c3d911c7e994909cdc3bea639a018af).

**Comment by AMIOL7** [comment]
@vismate I have played around with your idea for camera panning, there is a problem with it in my opinion:

1. I also have the same issue we had, when we first looked at the LitiEngine: the further mouse gets from the pont i pressed the RMB, the further the image gets from the mouse

**Comment by vismate** [comment]
> I also have the same issue we had, when we first looked at the LitiEngine: the further mouse gets from the pont i pressed the RMB, the further the image gets from the mouse

Yes, that's what happens unfortunately. Although a could not find a solution for it. My code is based upon a bog-standard Unity example so I don't know whether it has anything to do with how LITIEngine works, or it is just a thing that commonly happens with all 2D game engines in general.

In my opinion it still feels way nicer (on my machines, with my setups) then the current implementation. So maybe we should keep it around until we come up with a better one.

I'd like to see things starting to come together, so I'd lower this particular problem's priority. Although I'd like to get your input on how acceptable it is.

**Comment by vismate** [comment]
Fixed the problem! In my code change ```double scale = 1.0/cam.getZoom();``` to ```double scale = 1.0/cam.getRenderScale();```

This combines the camera's zoom with the game's render scale, so the cursor can be perfectly mapped to points on the map.
(My suspicion all along was, that there's a mismatch between zoom level and actual map coordinates.)

**Comment by AMIOL7** [comment]
It indeed works. I have also uploaded some basics for the zooming feature, but for some reason, I do not see it being applied does anyone have any ideas? @vismate @pszi @bgdxqi

**Comment by vismate** [comment]
It works fine for me. Although not for text. Try it with a rectangle or some shape. Also, I think ```MULTIPLIER``` is way to high. decrease it for smooth zooming! (0.05 works fine for me)

**Comment by AMIOL7** [comment]
I can't modify the multiplier as I do not see the zooming taking effect

**Comment by vismate** [comment]
### I can see it take effect:
![Recording 2022-10-23 at 17 03 02](https://user-images.githubusercontent.com/70141135/197399583-da4dc74a-e2ab-40b7-afb5-ed04a44ed98e.gif)

**Comment by AMIOL7** [comment]
Does it work for you with image?

**Comment by vismate** [comment]
I do not have an image. The image file you use is not in the repo. But will check.

**Comment by AMIOL7** [comment]
It seems that zoom does not work on images

**Comment by vismate** [comment]
It doesn't work on images/text whose size is not given in map coordinates. I suspect we'll need to render these to a texture. (Or something equivalent in LITIEngine). Basically we have to place them into the game world.

The zoom feature itself works fine though.

**Comment by AMIOL7** [comment]
Yes, I have added a text, and it works now
