### ISSUE TITLE
Final issue topic + versioning

### ISSUE THREAD

**Issue by pszi** [AMIOL7/ELME#61]
In this issue, discuss any last minor details that can quickly be resolved. If there's nothing notable, get ready to make a versioned release, and choose the scope: v1.0.0 or v0.1.0, perhaps something different? I will be making the release and closing the issue by the deadline of 6pm if nobody else does it before me.

**Comment by AMIOL7** [comment]
Since version is in form MAJOR.MINOR.PATCH, v1.0.0 is a better option

**Comment by pszi** [comment]
I see, but I think this shouldn't be considered a full release because it doesn't have all the features we planned it to have. Also, optionally alpha/beta can be used to signify it's current status. My vote is on "alpha 0.1.0"

**Comment by AMIOL7** [comment]
> I see, but I think this shouldn't be considered a full release because it doesn't have all the features we planned it to have. Also, optionally alpha/beta can be used to signify it's current status. My vote is on "alpha 0.1.0"

I see no problem with not having all features that we wanted, but I can agree with your option

**Comment by vismate** [comment]
We could also just not make a manual release. Its not part of the assignment.

**Comment by AMIOL7** [comment]
> We could also just not make a manual release. Its not part of the assignment. 

And there is no reason to wait for decision on making a manual release, as the assignment requires a link to GitHub to be submitted

**Comment by vismate** [comment]
> > We could also just not make a manual release. Its not part of the assignment. 
> 
> And there is no reason to wait for decision on making a manual release, as the assignment requires a link to GitHub to be submitted

The links are already submitted. Submitted it this morning.

**Comment by pszi** [comment]
It is true that this is not required, however in my honest opinion it would be much nicer and tidier if we wrapped up the project in a meaningful way, it doesn't need much work, and it might even be worth half a point.

**Comment by vismate** [comment]
> It is true that this is not required, however in my honest opinion it would be much nicer and tidier if we wrapped up the project in a meaningful way, it doesn't need much work, and it might even be worth half a point.

Maybe annotate the latest automatic release with a version number then.

**Comment by pszi** [comment]
I ended up naming it alpha v1.0.0 by mistake, but I think it's fine this way :smile:
